# Generated by Django 4.2.5 on 2023-11-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0009_alter_componenteproducto_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_compra',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
