# Generated by Django 4.2.5 on 2023-11-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0010_alter_producto_precio_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_materiaprima',
            field=models.BooleanField(default=False),
        ),
    ]
