# Generated by Django 4.2.5 on 2023-11-23 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0011_producto_es_materiaprima'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='es_materiaprima',
            new_name='es_materia_prima',
        ),
    ]
