# Generated by Django 4.2.5 on 2023-12-08 12:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0012_rename_es_materiaprima_producto_es_materia_prima'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_compra', models.DecimalField(decimal_places=4, max_digits=10)),
                ('fecha_inicio', models.DateField(default=datetime.datetime.now)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='Producto.producto')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
                'get_latest_by': 'fecha_inicio',
            },
        ),
    ]
