# Generated by Django 4.2.5 on 2023-12-08 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0013_historialprecio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistorialPrecio',
        ),
    ]
