# Generated by Django 4.2.5 on 2023-12-15 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0014_delete_historialprecio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre']},
        ),
    ]
