# Generated by Django 4.2.5 on 2023-11-14 20:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Producto', '0010_alter_producto_precio_compra'),
        ('Clientes', '0002_cliente_saldo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo_documento', models.CharField(choices=[('envio', 'Envío'), ('factura', 'Factura')], max_length=7)),
                ('tipo_pago', models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito')], max_length=7)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('cheque', 'Cheque'), ('deposito', 'Depósito')], max_length=8)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paga_con', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cambio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('dias_credito', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devolucion', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Ventas.venta')),
            ],
        ),
    ]
