# Generated by Django 4.2.5 on 2023-11-15 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0002_alter_venta_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleventa',
            options={'verbose_name': 'detalle venta', 'verbose_name_plural': 'detalles venta'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'verbose_name': 'venta', 'verbose_name_plural': 'ventas'},
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterOrderWithRespectTo(
            name='venta',
            order_with_respect_to='fecha_creacion',
        ),
        migrations.AlterOrderWithRespectTo(
            name='detalleventa',
            order_with_respect_to='created',
        ),
    ]
