# Generated by Django 4.2.5 on 2023-11-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0003_alter_detalleventa_options_alter_venta_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha_creacion',
            field=models.DateField(max_length=255),
        ),
    ]
