# Generated by Django 4.2.5 on 2023-11-19 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0007_cobro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobro',
            name='es_abono',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venta',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
