# Generated by Django 4.2.5 on 2023-11-21 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0010_venta_saldo_pendiente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon', models.TextField()),
                ('fecha_anulacion', models.DateTimeField(auto_now_add=True)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anulacion', to='Ventas.venta')),
            ],
        ),
    ]
