# Generated by Django 4.2.5 on 2023-12-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0014_cobro_anulado_anulacioncobro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobro',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
