# Generated by Django 4.2.5 on 2023-12-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0016_alter_detalleventa_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobro',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
