# Generated by Django 4.2.5 on 2023-12-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0017_alter_cobro_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='precio_compra_en_venta',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
