# Generated by Django 4.2.5 on 2023-12-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0018_detalleventa_precio_compra_en_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='descuento',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
