# Generated by Django 4.2.5 on 2023-12-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0019_alter_detalleventa_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
