# Generated by Django 4.2.5 on 2023-12-15 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0002_proveedor_saldo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['nombre'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
    ]
