# Generated by Django 4.2.5 on 2023-12-17 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vendedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendedor',
            options={'ordering': ['nombre'], 'verbose_name': 'vendedor', 'verbose_name_plural': 'vendedores'},
        ),
    ]
