# Generated by Django 4.2.5 on 2023-12-15 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0003_alter_cliente_correo_alter_cliente_nit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre']},
        ),
    ]
